### PR TITLE
fix!: remove serviceClasses

### PR DESCRIPTION
**Pull request by EndBug**
Ref #58 

After this PR is merged, `serviceClasses` will no longer be exported, even though it'll still be accessible via `Service.getAll()`. This is to encourage users to get service classes using `Service.get()` with aliases, instead of relying on internal class names.

From now on, changes to internal class names should not be marked as breaking changes, since the intended way of getting them is through aliases.

### CODE REVIEW

**Comment by Snazzah** [comment]
Should there be a way for TypeScript users to get the types for service classes and not necessarily get the class itself from the index? There might be a way to define overrides for `Service.get` in order for TS to get the right class.

**Comment by EndBug** [comment]
Hmmmm, you're right, I didn't think about that...
I'll look into it

**Comment by EndBug** [comment]
Ok, so here's what I've changed.
The source code now contains a file that generates a list with every alias and its class, so that it can be used as a type for the `Service.get` method. That method still uses the same code to actually get the class, but now has a type overload that allows you to get autocompletion on aliases, and the proper typing for the resulting class. If another string is used, it will go back to the old version, which returns a generic `null | typeof Service` (which is also what appears in the web docs, since using the other signature would result in every service type being listed)

The file is not automatically updated in the build script, to avoid unintentional changes being pushed: the `build:source` script has to be run manually. To avoid releasing with an outdated list, the tests will fail when that's the case (so don't dismiss the tests!)

What do you think?

**Review by Snazzah — APPROVED** [review]
A bit awkward, but the result works well.

**Pull request merged**
